apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-deployment
  labels:
    app: vproapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp-deployment
  template:
    metadata:
      labels:
        app: vproapp-deployment
    spec:
      containers:
      - name: vproapp
        image: vprofile/vprofileapp:V1
        ports:
        - name: app-port
          containerPort: 8080

      initContainers:
      - name: init-mydb
        image: busybox
        command: ['sh', '-c', 'until nslookup vprodb; do echo waiting for mydb; sleep 2; done;']
      - name: init-memcache
        image: busybox
        command: ['sh', '-c', 'until nslookup vprocache01; do echo waiting for mydb; sleep 2; done;']