apiVersion: apps/v1
kind: Deployment
metadata:
  name: mem-deployment
  labels:
    app: mem-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mem-deployment
  template:
    metadata:
      labels:
        app: mem-deployment
    spec:
      containers:
      - name: vpromc
        image: memcached
        ports:
        - name: mem-port
          containerPort: 11211
